### ISSUE TITLE
How to change font

### ISSUE THREAD

**Issue by Zefty** [MarcoPixel/SysDash#13]

**Comment by MarcoPixel** [comment]
To change the font, right-click the skin and click on **Open variables file** 
or go under **Documents/Rainmeter/Skins/SysDash/@Resources** and open **variables.ini.**

In there you will find different variables and there are also two font variables:
**FontClock** and **Font**

Replace the text behind the = with the name of your font which is installed on your system.

**Comment by Zefty** [comment]
Hi i've already looked at that file but there is no such thing as fontclock and font. Do i manually add them ?
