### ISSUE TITLE
Weather does not show, gets timeout and "N/A" shown in skin

### ISSUE THREAD

**Issue by AriinPHD** [marcopixel/SysDash#17]
Reference to issue #3 .

I'm also seeing this issue.

Debug: Unable to read file: C:\Users\Ariin\Documents\Rainmeter\Skins\SysDash\@Resources\include\MeasureStyling.inc (SysDash\Weather\weather.ini)

The file MeasureStyling.inc is missing entirely from the (at)Resources folder.

Other than that, this happens (Debug):
Fetching: https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="Oslo, Norway") and u="C" (SysDash\Weather\weather.ini - [MeasureWeather])

then:
(Fetch error) The operation timed out  (ErrorCode=12002) (SysDash\Weather\weather.ini - [MeasureWeather])

Rainmeter v.
4.1.0 r2989 64-bit (Nov  6 2017)
Windows 10 Pro 64-bit (build 16299)
Skin  v:
Latest. Downloaded today, 1 hour ago from posting this.

**Comment by MarcoPixel** [comment]
@AriinPHD Try downloading the latest Rainmeter Beta and if that doesn't work reinstall the skin.
