### ISSUE TITLE
Network Download/Upload speed

### ISSUE THREAD

**Issue by sdkrocks** [marcopixel/SysDash#20]
For me, the network download and upload speed is not showing correctly. Any fix? Thanks! 

![networkskin](https://user-images.githubusercontent.com/20824636/35198470-67e5888e-febd-11e7-8984-d9b5f51c3fbb.PNG)

![speedtest](https://user-images.githubusercontent.com/20824636/35198480-884a93bc-febd-11e7-99ea-824a8516a59c.PNG)

**Comment by dragonejt** [comment]
When you are doing a speed test, that shows your maximum D/U speeds on your ISP. The widget displays current D/U speeds from Task Manager. If you download a steam game or something it will probably get close to that max. Also keep in mind bits vs bytes. 1 byte = 8 bits i think.
