### ISSUE TITLE
Changing the height of the background

### ISSUE THREAD

**Issue by TX112** [marcopixel/SysDash#22]
Have the problem that I can't change the height of the background, how do I do that?

**Comment by MarcoPixel** [comment]
The height of the background is affected by the screens size, but you can change it manually by replacing `W=#WORKAREAWIDTH#` with `W=200` by editing the skin file.

If you don't know how you can do this, check out the [Customizing Guide](https://docs.rainmeter.net/manual-beta/getting-started/customizing/) to modify it yourself.

**Comment by TX112** [comment]
Thank you for the Help :)

**Comment by Ciamician** [comment]
@MarcoPixel Don't you mean changing `H=#WORKAREAHEIGHT#` to `H=<height of screen resolution>`

**Comment by marcopixel** [comment]
@SanderHolvoet `#WORKAREAHEIGHT#` is the height of the desktop minus the taskbar.

https://docs.rainmeter.net/tips/screen-position-variables/
