### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by Groakk** [MarcoPixel/SysDash#3]
I'm having troubles getting the skin to find my location. I've tried many different formats and there is still no weather/temperature to display. It only shows N/A for temp.

**Comment by MarcoPixel** [comment]
Could you please send a screenshot from the debug log of Rainmeter (https://docs.rainmeter.net/manual/user-interface/about/) and post it in here.

Also please write down your OS version, Rainmeter version and the city name you want to use.

**Comment by MarcoPixel** [comment]
@FatKontroller You have to input the city and then press Enter to confirm it. Try it again and check if it works :)

**Comment by FatKontroller** [comment]
I love you! Thank you! And thank you for the VERY quick reply!!!!!

**Comment by MarcoPixel** [comment]
@FatKontroller No problem, that's what Github is great for. I get like an instant notification as soon someone writes something on my repos.

**Comment by FatKontroller** [comment]
That's great. Thank you again! Also just installed your visualizer, really looks great on my new portrait monitor. :)

**Comment by MarcoPixel** [comment]
It seems that issue got fixed as there was no response from the original creator so im gonna close this issue as fixed. Please create a new issue or comment on this one to reopen it.

**Comment by AriinPHD** [comment]
Apologies but I am re-opening this issue. This is the error seen (missing file):

Unable to read file: C:\Users\Ariin\Documents\Rainmeter\Skins\SysDash\@Resources\include\MeasureStyling.inc (SysDash\Weather\weather.ini)

The file MeasureStyling.inc is missing entirely.

Other than that, this happens (Debug):

Fetching: https://query.yahooapis.com/v1/public/yql?q=select * from weather.forecast where woeid in (select woeid from geo.places(1) where text="Oslo, Norway") and u="C" (SysDash\Weather\weather.ini - [MeasureWeather])

then:

(Fetch error) The operation timed out  (ErrorCode=12002) (SysDash\Weather\weather.ini - [MeasureWeather])
