### ISSUE TITLE
How to force Background to be behind widgets?

### ISSUE THREAD

**Issue by DJBenz** [marcopixel/SysDash#39]
Sorry if a dumb question, new to Rainmeter, but how can I force the background to always be behind the widgets? I got the SysDash skin set up and running great, but when I rebooted, all but CPU Temp were behind the background making them look greyed out. I've simply turned it off for the moment, but it looks so much better with the contrast the background provides.

Thanks for this great skin, I'm loving it!

**Comment by DL-webmaster** [comment]
If you haven't figured it out by now, open the Manager for Rainmeter,, open the SysDash Background to highlight the background.ini file. The settings on the right side should populate, change Position to Bottom.

**Comment by marcopixel** [comment]
Problem seems to be fixed, closing issue.
