### ISSUE TITLE
As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 

### ISSUE THREAD

**Issue by Ezeta17** [marcopixel/SysDash#49]
Important EOL Notice: As of Thursday, Jan. 3, 2019, the weather.yahooapis.com and query.yahooapis.com for Yahoo Weather API will be retired. 
To continue using our free Yahoo Weather APIs, use https://weather-ydn-yql.media.yahoo.com/forecastrss. Follow below instructions to get credentials and onboard to this free Yahoo Weather API service.

[https://developer.yahoo.com/weather/](https://developer.yahoo.com/weather/)

**Comment by marcopixel** [comment]
Will be fixed in the future, check #56 for more information.
