### ISSUE TITLE
[Request] Open File Directory & Easier Settings Inputs

### ISSUE THREAD

**Issue by Umarrii** [MarcoPixel/SysDash#5]
Liking the skin so far, just some additional requests.

- Clicking the hard drive space will open the hard drive's directory, (C:\ or D:\)
- In the Settings Menu, it would be nice to be able to also input values rather than only being able to use the scroll bar.

**Comment by MarcoPixel** [comment]
@Umarrii The features you suggested are now implemented in the code, if you want to use them please refer to the manual installation guide in the README.md file or wait for the next release.

For the input fields the only exception is the opacity slider as it would require additional calculation measures and it thought it wouldn't be that neccessary there as it only ranges between 0-100 and you could fine-adjust via mouse wheel.

As both features are now implemented, i'm gonna close this issue now.
