### ISSUE TITLE
Drive free space not correct

### ISSUE THREAD

**Issue by jojosteez** [MarcoPixel/SysDash#6]
Love the skin.  Just having one issue.

The drives meter isn't reading correct for me.  If it said "free" instead of "used" it would be closer, but still not exact.  I tried looking in drive.ini to change the wording but didn't see it in there.   Also, you can see that the bar graph isn't matching.  The C: drive bar is around 80% filled, but the numbers show 90.5 GB out of 499.6 GB which is about 20%.   I've attached a screenshot.  Thanks.

![2017-07-05_02-55-48](https://user-images.githubusercontent.com/16627224/27854741-7fbaf076-612d-11e7-8ef7-cc271e126aca.png)

Windows 10, Rainmeter 4.1beta r2822

**Comment by MarcoPixel** [comment]
@jojosteez Thanks for your feedback!

This will be fixed in the next release, if you want to use it now click on the link above this comment and then replace the file **drive.ini** with the contents of this link.

**Comment by jojosteez** [comment]
Thank you so much!  Updated the file and it's reading correctly.  Thanks again!
