### ISSUE TITLE
[Request] Open Volume Mixer by click on Volume Icon?

### ISSUE THREAD

**Issue by lumbeecheraw75** [MarcoPixel/SysDash#8]
I know this was a thing in another skin that I tried out. I was wondering if you could implement opening the Volume Mixer by right clicking the icon for the Volume Slider possibly, similarly to how your recycle bin skin works

**Comment by lumbeecheraw75** [comment]
the code from the other skin that does this is

`[meterTitle]
Meter=String
MeterStyle=StyleTitle
Text="volume"
W=100
LeftMouseUpAction=!Execute ["SndVol.exe"]
ToolTipText="Open Sound Mixer"`

I tried to implement this myself, but i'm a code noob.

**Comment by MarcoPixel** [comment]
@lumbeecheraw75 Thanks for you suggestion.

The features you suggested are now implemented in the code, if you want to use them please refer to the manual installation guide in the README.md file or wait for the next release.

As the feature is now implemented, i will close this issue.

**Comment by lumbeecheraw75** [comment]
Thank you! Works great
